version: "2"
linters:
  enable:
    - dupword
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
  disable:
    - errcheck
  settings:
    gosec:
      excludes:
        - G204
        - G305
        - G306
        - G402
        - G404
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
