name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  checks:
    name: Project Checks
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
      with:
        path: src/github.com/containerd/fifo # project-checks depends on GOPATH mode
        fetch-depth: 25
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
    - uses: containerd/project-checks@v1.1.0
      with:
        working-directory: src/github.com/containerd/fifo # project-checks depends on GOPATH mode

  linters:
    name: Linters
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-22.04, macos-14, windows-2022]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set env
        shell: bash
        run: |
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        go-version: [1.20.x, 1.22.x]
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - run: make test
